# Generated by Django 4.2.2 on 2023-08-15 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_orderitemtemp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='order',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='user',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='user_address',
        ),
        migrations.RemoveField(
            model_name='purchaseproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='purchaseproduct',
            name='purchase',
        ),
        migrations.DeleteModel(
            name='OrderItemTemp',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
        migrations.DeleteModel(
            name='PurchaseProduct',
        ),
    ]
