# Generated by Django 4.2.2 on 2023-08-16 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.IntegerField(default=models.F('id'), unique=True),
        ),
    ]
