# Generated by Django 4.2.2 on 2023-08-17 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_alter_order_transaction_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.product')),
            ],
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='address',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='order',
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='OrderItemTemp',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
