# Generated by Django 4.2.2 on 2023-08-17 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_heart_remove_purchase_address_remove_purchase_order_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Heart',
        ),
    ]
